name: EBAC CI Mobile

on:
  push:
    branches: [ ci ]

  workflow_dispatch:

jobs:
  mobile-tests:
    runs-on: ubuntu-latest

    env:
      SAUCE_USERNAME: "ooauth-geleiao.snap-9808a"
      SAUCE_ACCESS_KEY: "3bff4f90-da87-47fe-83b1-27907c9cfb09"
      SAUCE_APP: "LojaEBAC-sim.zip"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run mobile tests on SauceLabs
        run: npm run test